// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/location/location.proto

package location

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Heading       float64                `protobuf:"fixed64,5,opt,name=heading,proto3" json:"heading,omitempty"`
	Speed         float64                `protobuf:"fixed64,6,opt,name=speed,proto3" json:"speed,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_proto_location_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateLocationRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *UpdateLocationRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *UpdateLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateLocationRequest) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *UpdateLocationRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *UpdateLocationRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UpdateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationResponse) Reset() {
	*x = UpdateLocationResponse{}
	mi := &file_proto_location_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationResponse) ProtoMessage() {}

func (x *UpdateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_proto_location_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{2}
}

func (x *GetLocationRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type LocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Heading       float64                `protobuf:"fixed64,4,opt,name=heading,proto3" json:"heading,omitempty"`
	Speed         float64                `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationResponse) Reset() {
	*x = LocationResponse{}
	mi := &file_proto_location_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationResponse) ProtoMessage() {}

func (x *LocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationResponse.ProtoReflect.Descriptor instead.
func (*LocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{3}
}

func (x *LocationResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *LocationResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationResponse) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *LocationResponse) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *LocationResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type GetNearbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	EntityType    string                 `protobuf:"bytes,4,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyRequest) Reset() {
	*x = GetNearbyRequest{}
	mi := &file_proto_location_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyRequest) ProtoMessage() {}

func (x *GetNearbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyRequest.ProtoReflect.Descriptor instead.
func (*GetNearbyRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{4}
}

func (x *GetNearbyRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetNearbyRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetNearbyRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *GetNearbyRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *GetNearbyRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetNearbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*NearbyEntity        `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyResponse) Reset() {
	*x = GetNearbyResponse{}
	mi := &file_proto_location_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyResponse) ProtoMessage() {}

func (x *GetNearbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyResponse.ProtoReflect.Descriptor instead.
func (*GetNearbyResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{5}
}

func (x *GetNearbyResponse) GetEntities() []*NearbyEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type NearbyEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,4,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyEntity) Reset() {
	*x = NearbyEntity{}
	mi := &file_proto_location_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyEntity) ProtoMessage() {}

func (x *NearbyEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyEntity.ProtoReflect.Descriptor instead.
func (*NearbyEntity) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{6}
}

func (x *NearbyEntity) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *NearbyEntity) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *NearbyEntity) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *NearbyEntity) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

type GetRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        *Coordinate            `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   *Coordinate            `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteRequest) Reset() {
	*x = GetRouteRequest{}
	mi := &file_proto_location_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteRequest) ProtoMessage() {}

func (x *GetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteRequest.ProtoReflect.Descriptor instead.
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{7}
}

func (x *GetRouteRequest) GetOrigin() *Coordinate {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *GetRouteRequest) GetDestination() *Coordinate {
	if x != nil {
		return x.Destination
	}
	return nil
}

type GetRouteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DistanceKm      float64                `protobuf:"fixed64,1,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	DurationMinutes float64                `protobuf:"fixed64,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Polyline        []*Coordinate          `protobuf:"bytes,3,rep,name=polyline,proto3" json:"polyline,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRouteResponse) Reset() {
	*x = GetRouteResponse{}
	mi := &file_proto_location_location_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteResponse) ProtoMessage() {}

func (x *GetRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteResponse.ProtoReflect.Descriptor instead.
func (*GetRouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{8}
}

func (x *GetRouteResponse) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *GetRouteResponse) GetDurationMinutes() float64 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *GetRouteResponse) GetPolyline() []*Coordinate {
	if x != nil {
		return x.Polyline
	}
	return nil
}

type CalculateETARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        *Coordinate            `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   *Coordinate            `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateETARequest) Reset() {
	*x = CalculateETARequest{}
	mi := &file_proto_location_location_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateETARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateETARequest) ProtoMessage() {}

func (x *CalculateETARequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateETARequest.ProtoReflect.Descriptor instead.
func (*CalculateETARequest) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{9}
}

func (x *CalculateETARequest) GetOrigin() *Coordinate {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *CalculateETARequest) GetDestination() *Coordinate {
	if x != nil {
		return x.Destination
	}
	return nil
}

type CalculateETAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EtaMinutes    float64                `protobuf:"fixed64,1,opt,name=eta_minutes,json=etaMinutes,proto3" json:"eta_minutes,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,2,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateETAResponse) Reset() {
	*x = CalculateETAResponse{}
	mi := &file_proto_location_location_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateETAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateETAResponse) ProtoMessage() {}

func (x *CalculateETAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateETAResponse.ProtoReflect.Descriptor instead.
func (*CalculateETAResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{10}
}

func (x *CalculateETAResponse) GetEtaMinutes() float64 {
	if x != nil {
		return x.EtaMinutes
	}
	return 0
}

func (x *CalculateETAResponse) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_proto_location_location_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{11}
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_proto_location_location_proto protoreflect.FileDescriptor

const file_proto_location_location_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/location/location.proto\x12\blocation\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\x15UpdateLocationRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aheading\x18\x05 \x01(\x01R\aheading\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\x01R\x05speed\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"2\n" +
	"\x16UpdateLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x12GetLocationRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"\xd8\x01\n" +
	"\x10LocationResponse\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x01R\aheading\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12=\n" +
	"\flast_updated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\xa0\x01\n" +
	"\x10GetNearbyRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\x12\x1f\n" +
	"\ventity_type\x18\x04 \x01(\tR\n" +
	"entityType\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"G\n" +
	"\x11GetNearbyResponse\x122\n" +
	"\bentities\x18\x01 \x03(\v2\x16.location.NearbyEntityR\bentities\"\x86\x01\n" +
	"\fNearbyEntity\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1f\n" +
	"\vdistance_km\x18\x04 \x01(\x01R\n" +
	"distanceKm\"w\n" +
	"\x0fGetRouteRequest\x12,\n" +
	"\x06origin\x18\x01 \x01(\v2\x14.location.CoordinateR\x06origin\x126\n" +
	"\vdestination\x18\x02 \x01(\v2\x14.location.CoordinateR\vdestination\"\x90\x01\n" +
	"\x10GetRouteResponse\x12\x1f\n" +
	"\vdistance_km\x18\x01 \x01(\x01R\n" +
	"distanceKm\x12)\n" +
	"\x10duration_minutes\x18\x02 \x01(\x01R\x0fdurationMinutes\x120\n" +
	"\bpolyline\x18\x03 \x03(\v2\x14.location.CoordinateR\bpolyline\"{\n" +
	"\x13CalculateETARequest\x12,\n" +
	"\x06origin\x18\x01 \x01(\v2\x14.location.CoordinateR\x06origin\x126\n" +
	"\vdestination\x18\x02 \x01(\v2\x14.location.CoordinateR\vdestination\"X\n" +
	"\x14CalculateETAResponse\x12\x1f\n" +
	"\veta_minutes\x18\x01 \x01(\x01R\n" +
	"etaMinutes\x12\x1f\n" +
	"\vdistance_km\x18\x02 \x01(\x01R\n" +
	"distanceKm\"F\n" +
	"\n" +
	"Coordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude2\xe1\x03\n" +
	"\x0fLocationService\x12S\n" +
	"\x0eUpdateLocation\x12\x1f.location.UpdateLocationRequest\x1a .location.UpdateLocationResponse\x12G\n" +
	"\vGetLocation\x12\x1c.location.GetLocationRequest\x1a\x1a.location.LocationResponse\x12K\n" +
	"\x10GetNearbyDrivers\x12\x1a.location.GetNearbyRequest\x1a\x1b.location.GetNearbyResponse\x12Q\n" +
	"\x0eStreamLocation\x12\x1f.location.UpdateLocationRequest\x1a\x1a.location.LocationResponse(\x010\x01\x12A\n" +
	"\bGetRoute\x12\x19.location.GetRouteRequest\x1a\x1a.location.GetRouteResponse\x12M\n" +
	"\fCalculateETA\x12\x1d.location.CalculateETARequest\x1a\x1e.location.CalculateETAResponseB\x11Z\x0fpkg/pb/locationb\x06proto3"

var (
	file_proto_location_location_proto_rawDescOnce sync.Once
	file_proto_location_location_proto_rawDescData []byte
)

func file_proto_location_location_proto_rawDescGZIP() []byte {
	file_proto_location_location_proto_rawDescOnce.Do(func() {
		file_proto_location_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_location_location_proto_rawDesc), len(file_proto_location_location_proto_rawDesc)))
	})
	return file_proto_location_location_proto_rawDescData
}

var file_proto_location_location_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_location_location_proto_goTypes = []any{
	(*UpdateLocationRequest)(nil),  // 0: location.UpdateLocationRequest
	(*UpdateLocationResponse)(nil), // 1: location.UpdateLocationResponse
	(*GetLocationRequest)(nil),     // 2: location.GetLocationRequest
	(*LocationResponse)(nil),       // 3: location.LocationResponse
	(*GetNearbyRequest)(nil),       // 4: location.GetNearbyRequest
	(*GetNearbyResponse)(nil),      // 5: location.GetNearbyResponse
	(*NearbyEntity)(nil),           // 6: location.NearbyEntity
	(*GetRouteRequest)(nil),        // 7: location.GetRouteRequest
	(*GetRouteResponse)(nil),       // 8: location.GetRouteResponse
	(*CalculateETARequest)(nil),    // 9: location.CalculateETARequest
	(*CalculateETAResponse)(nil),   // 10: location.CalculateETAResponse
	(*Coordinate)(nil),             // 11: location.Coordinate
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_proto_location_location_proto_depIdxs = []int32{
	12, // 0: location.UpdateLocationRequest.timestamp:type_name -> google.protobuf.Timestamp
	12, // 1: location.LocationResponse.last_updated:type_name -> google.protobuf.Timestamp
	6,  // 2: location.GetNearbyResponse.entities:type_name -> location.NearbyEntity
	11, // 3: location.GetRouteRequest.origin:type_name -> location.Coordinate
	11, // 4: location.GetRouteRequest.destination:type_name -> location.Coordinate
	11, // 5: location.GetRouteResponse.polyline:type_name -> location.Coordinate
	11, // 6: location.CalculateETARequest.origin:type_name -> location.Coordinate
	11, // 7: location.CalculateETARequest.destination:type_name -> location.Coordinate
	0,  // 8: location.LocationService.UpdateLocation:input_type -> location.UpdateLocationRequest
	2,  // 9: location.LocationService.GetLocation:input_type -> location.GetLocationRequest
	4,  // 10: location.LocationService.GetNearbyDrivers:input_type -> location.GetNearbyRequest
	0,  // 11: location.LocationService.StreamLocation:input_type -> location.UpdateLocationRequest
	7,  // 12: location.LocationService.GetRoute:input_type -> location.GetRouteRequest
	9,  // 13: location.LocationService.CalculateETA:input_type -> location.CalculateETARequest
	1,  // 14: location.LocationService.UpdateLocation:output_type -> location.UpdateLocationResponse
	3,  // 15: location.LocationService.GetLocation:output_type -> location.LocationResponse
	5,  // 16: location.LocationService.GetNearbyDrivers:output_type -> location.GetNearbyResponse
	3,  // 17: location.LocationService.StreamLocation:output_type -> location.LocationResponse
	8,  // 18: location.LocationService.GetRoute:output_type -> location.GetRouteResponse
	10, // 19: location.LocationService.CalculateETA:output_type -> location.CalculateETAResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_location_location_proto_init() }
func file_proto_location_location_proto_init() {
	if File_proto_location_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_location_location_proto_rawDesc), len(file_proto_location_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_location_location_proto_goTypes,
		DependencyIndexes: file_proto_location_location_proto_depIdxs,
		MessageInfos:      file_proto_location_location_proto_msgTypes,
	}.Build()
	File_proto_location_location_proto = out.File
	file_proto_location_location_proto_goTypes = nil
	file_proto_location_location_proto_depIdxs = nil
}
