// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ride/ride.proto

package ride

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RideStatus int32

const (
	RideStatus_REQUESTED       RideStatus = 0
	RideStatus_MATCHED         RideStatus = 1
	RideStatus_DRIVER_ACCEPTED RideStatus = 2
	RideStatus_DRIVER_ARRIVING RideStatus = 3
	RideStatus_DRIVER_ARRIVED  RideStatus = 4
	RideStatus_IN_PROGRESS     RideStatus = 5
	RideStatus_COMPLETED       RideStatus = 6
	RideStatus_CANCELLED       RideStatus = 7
)

// Enum value maps for RideStatus.
var (
	RideStatus_name = map[int32]string{
		0: "REQUESTED",
		1: "MATCHED",
		2: "DRIVER_ACCEPTED",
		3: "DRIVER_ARRIVING",
		4: "DRIVER_ARRIVED",
		5: "IN_PROGRESS",
		6: "COMPLETED",
		7: "CANCELLED",
	}
	RideStatus_value = map[string]int32{
		"REQUESTED":       0,
		"MATCHED":         1,
		"DRIVER_ACCEPTED": 2,
		"DRIVER_ARRIVING": 3,
		"DRIVER_ARRIVED":  4,
		"IN_PROGRESS":     5,
		"COMPLETED":       6,
		"CANCELLED":       7,
	}
)

func (x RideStatus) Enum() *RideStatus {
	p := new(RideStatus)
	*p = x
	return p
}

func (x RideStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RideStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ride_ride_proto_enumTypes[0].Descriptor()
}

func (RideStatus) Type() protoreflect.EnumType {
	return &file_proto_ride_ride_proto_enumTypes[0]
}

func (x RideStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RideStatus.Descriptor instead.
func (RideStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{0}
}

type RideRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RiderId         string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	PickupLocation  *Location              `protobuf:"bytes,2,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	DropoffLocation *Location              `protobuf:"bytes,3,opt,name=dropoff_location,json=dropoffLocation,proto3" json:"dropoff_location,omitempty"`
	VehicleType     string                 `protobuf:"bytes,4,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RideRequest) Reset() {
	*x = RideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideRequest) ProtoMessage() {}

func (x *RideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideRequest.ProtoReflect.Descriptor instead.
func (*RideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{0}
}

func (x *RideRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RideRequest) GetPickupLocation() *Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *RideRequest) GetDropoffLocation() *Location {
	if x != nil {
		return x.DropoffLocation
	}
	return nil
}

func (x *RideRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *RideRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type AcceptRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRideRequest) Reset() {
	*x = AcceptRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRideRequest) ProtoMessage() {}

func (x *AcceptRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRideRequest.ProtoReflect.Descriptor instead.
func (*AcceptRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *AcceptRideRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type StartRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRideRequest) Reset() {
	*x = StartRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRideRequest) ProtoMessage() {}

func (x *StartRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRideRequest.ProtoReflect.Descriptor instead.
func (*StartRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{2}
}

func (x *StartRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *StartRideRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type CompleteRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	FinalLocation *Location              `protobuf:"bytes,3,opt,name=final_location,json=finalLocation,proto3" json:"final_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRideRequest) Reset() {
	*x = CompleteRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRideRequest) ProtoMessage() {}

func (x *CompleteRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRideRequest.ProtoReflect.Descriptor instead.
func (*CompleteRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *CompleteRideRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *CompleteRideRequest) GetFinalLocation() *Location {
	if x != nil {
		return x.FinalLocation
	}
	return nil
}

type CancelRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	CancelledBy   string                 `protobuf:"bytes,2,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRideRequest) Reset() {
	*x = CancelRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRideRequest) ProtoMessage() {}

func (x *CancelRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRideRequest.ProtoReflect.Descriptor instead.
func (*CancelRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *CancelRideRequest) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

func (x *CancelRideRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRideRequest) Reset() {
	*x = GetRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRideRequest) ProtoMessage() {}

func (x *GetRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRideRequest.ProtoReflect.Descriptor instead.
func (*GetRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{5}
}

func (x *GetRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

type GetActiveRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveRideRequest) Reset() {
	*x = GetActiveRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveRideRequest) ProtoMessage() {}

func (x *GetActiveRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveRideRequest.ProtoReflect.Descriptor instead.
func (*GetActiveRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{6}
}

func (x *GetActiveRideRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRideHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRideHistoryRequest) Reset() {
	*x = GetRideHistoryRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRideHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRideHistoryRequest) ProtoMessage() {}

func (x *GetRideHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRideHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetRideHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{7}
}

func (x *GetRideHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRideHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRideHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRideHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rides         []*RideResponse        `protobuf:"bytes,1,rep,name=rides,proto3" json:"rides,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRideHistoryResponse) Reset() {
	*x = GetRideHistoryResponse{}
	mi := &file_proto_ride_ride_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRideHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRideHistoryResponse) ProtoMessage() {}

func (x *GetRideHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRideHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetRideHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{8}
}

func (x *GetRideHistoryResponse) GetRides() []*RideResponse {
	if x != nil {
		return x.Rides
	}
	return nil
}

func (x *GetRideHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type RateRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating        float32                `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateRideRequest) Reset() {
	*x = RateRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateRideRequest) ProtoMessage() {}

func (x *RateRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateRideRequest.ProtoReflect.Descriptor instead.
func (*RateRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{9}
}

func (x *RateRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *RateRideRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RateRideRequest) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RateRideRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RateRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateRideResponse) Reset() {
	*x = RateRideResponse{}
	mi := &file_proto_ride_ride_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateRideResponse) ProtoMessage() {}

func (x *RateRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateRideResponse.ProtoReflect.Descriptor instead.
func (*RateRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{10}
}

func (x *RateRideResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EstimateRideRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PickupLocation  *Location              `protobuf:"bytes,1,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	DropoffLocation *Location              `protobuf:"bytes,2,opt,name=dropoff_location,json=dropoffLocation,proto3" json:"dropoff_location,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EstimateRideRequest) Reset() {
	*x = EstimateRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateRideRequest) ProtoMessage() {}

func (x *EstimateRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateRideRequest.ProtoReflect.Descriptor instead.
func (*EstimateRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{11}
}

func (x *EstimateRideRequest) GetPickupLocation() *Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *EstimateRideRequest) GetDropoffLocation() *Location {
	if x != nil {
		return x.DropoffLocation
	}
	return nil
}

type EstimateRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estimates     []*RideEstimate        `protobuf:"bytes,1,rep,name=estimates,proto3" json:"estimates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateRideResponse) Reset() {
	*x = EstimateRideResponse{}
	mi := &file_proto_ride_ride_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateRideResponse) ProtoMessage() {}

func (x *EstimateRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateRideResponse.ProtoReflect.Descriptor instead.
func (*EstimateRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{12}
}

func (x *EstimateRideResponse) GetEstimates() []*RideEstimate {
	if x != nil {
		return x.Estimates
	}
	return nil
}

type RideEstimate struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	VehicleType              string                 `protobuf:"bytes,1,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	EstimatedFareMin         float64                `protobuf:"fixed64,2,opt,name=estimated_fare_min,json=estimatedFareMin,proto3" json:"estimated_fare_min,omitempty"`
	EstimatedFareMax         float64                `protobuf:"fixed64,3,opt,name=estimated_fare_max,json=estimatedFareMax,proto3" json:"estimated_fare_max,omitempty"`
	EstimatedDurationMinutes float64                `protobuf:"fixed64,4,opt,name=estimated_duration_minutes,json=estimatedDurationMinutes,proto3" json:"estimated_duration_minutes,omitempty"`
	EstimatedDistanceKm      float64                `protobuf:"fixed64,5,opt,name=estimated_distance_km,json=estimatedDistanceKm,proto3" json:"estimated_distance_km,omitempty"`
	SurgeMultiplier          float64                `protobuf:"fixed64,6,opt,name=surge_multiplier,json=surgeMultiplier,proto3" json:"surge_multiplier,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RideEstimate) Reset() {
	*x = RideEstimate{}
	mi := &file_proto_ride_ride_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideEstimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideEstimate) ProtoMessage() {}

func (x *RideEstimate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideEstimate.ProtoReflect.Descriptor instead.
func (*RideEstimate) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{13}
}

func (x *RideEstimate) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *RideEstimate) GetEstimatedFareMin() float64 {
	if x != nil {
		return x.EstimatedFareMin
	}
	return 0
}

func (x *RideEstimate) GetEstimatedFareMax() float64 {
	if x != nil {
		return x.EstimatedFareMax
	}
	return 0
}

func (x *RideEstimate) GetEstimatedDurationMinutes() float64 {
	if x != nil {
		return x.EstimatedDurationMinutes
	}
	return 0
}

func (x *RideEstimate) GetEstimatedDistanceKm() float64 {
	if x != nil {
		return x.EstimatedDistanceKm
	}
	return 0
}

func (x *RideEstimate) GetSurgeMultiplier() float64 {
	if x != nil {
		return x.SurgeMultiplier
	}
	return 0
}

type StreamRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRideRequest) Reset() {
	*x = StreamRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRideRequest) ProtoMessage() {}

func (x *StreamRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRideRequest.ProtoReflect.Descriptor instead.
func (*StreamRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{14}
}

func (x *StreamRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

type RideUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RideId         string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	Status         RideStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=ride.RideStatus" json:"status,omitempty"`
	DriverLocation *Location              `protobuf:"bytes,3,opt,name=driver_location,json=driverLocation,proto3" json:"driver_location,omitempty"`
	EtaMinutes     float64                `protobuf:"fixed64,4,opt,name=eta_minutes,json=etaMinutes,proto3" json:"eta_minutes,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RideUpdate) Reset() {
	*x = RideUpdate{}
	mi := &file_proto_ride_ride_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideUpdate) ProtoMessage() {}

func (x *RideUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideUpdate.ProtoReflect.Descriptor instead.
func (*RideUpdate) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{15}
}

func (x *RideUpdate) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *RideUpdate) GetStatus() RideStatus {
	if x != nil {
		return x.Status
	}
	return RideStatus_REQUESTED
}

func (x *RideUpdate) GetDriverLocation() *Location {
	if x != nil {
		return x.DriverLocation
	}
	return nil
}

func (x *RideUpdate) GetEtaMinutes() float64 {
	if x != nil {
		return x.EtaMinutes
	}
	return 0
}

func (x *RideUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type RideResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RideId          string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	RiderId         string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId        string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status          RideStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=ride.RideStatus" json:"status,omitempty"`
	PickupLocation  *Location              `protobuf:"bytes,5,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	DropoffLocation *Location              `protobuf:"bytes,6,opt,name=dropoff_location,json=dropoffLocation,proto3" json:"dropoff_location,omitempty"`
	VehicleType     string                 `protobuf:"bytes,7,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	EstimatedFare   float64                `protobuf:"fixed64,8,opt,name=estimated_fare,json=estimatedFare,proto3" json:"estimated_fare,omitempty"`
	ActualFare      float64                `protobuf:"fixed64,9,opt,name=actual_fare,json=actualFare,proto3" json:"actual_fare,omitempty"`
	DistanceKm      float64                `protobuf:"fixed64,10,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	DurationMinutes float64                `protobuf:"fixed64,11,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	SurgeMultiplier float64                `protobuf:"fixed64,12,opt,name=surge_multiplier,json=surgeMultiplier,proto3" json:"surge_multiplier,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,16,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	RiderRating     float32                `protobuf:"fixed32,17,opt,name=rider_rating,json=riderRating,proto3" json:"rider_rating,omitempty"`
	DriverRating    float32                `protobuf:"fixed32,18,opt,name=driver_rating,json=driverRating,proto3" json:"driver_rating,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RideResponse) Reset() {
	*x = RideResponse{}
	mi := &file_proto_ride_ride_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideResponse) ProtoMessage() {}

func (x *RideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideResponse.ProtoReflect.Descriptor instead.
func (*RideResponse) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{16}
}

func (x *RideResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *RideResponse) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RideResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *RideResponse) GetStatus() RideStatus {
	if x != nil {
		return x.Status
	}
	return RideStatus_REQUESTED
}

func (x *RideResponse) GetPickupLocation() *Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *RideResponse) GetDropoffLocation() *Location {
	if x != nil {
		return x.DropoffLocation
	}
	return nil
}

func (x *RideResponse) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *RideResponse) GetEstimatedFare() float64 {
	if x != nil {
		return x.EstimatedFare
	}
	return 0
}

func (x *RideResponse) GetActualFare() float64 {
	if x != nil {
		return x.ActualFare
	}
	return 0
}

func (x *RideResponse) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *RideResponse) GetDurationMinutes() float64 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *RideResponse) GetSurgeMultiplier() float64 {
	if x != nil {
		return x.SurgeMultiplier
	}
	return 0
}

func (x *RideResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RideResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RideResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *RideResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *RideResponse) GetRiderRating() float32 {
	if x != nil {
		return x.RiderRating
	}
	return 0
}

func (x *RideResponse) GetDriverRating() float32 {
	if x != nil {
		return x.DriverRating
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_ride_ride_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{17}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_proto_ride_ride_proto protoreflect.FileDescriptor

const file_proto_ride_ride_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ride/ride.proto\x12\x04ride\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x01\n" +
	"\vRideRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x127\n" +
	"\x0fpickup_location\x18\x02 \x01(\v2\x0e.ride.LocationR\x0epickupLocation\x129\n" +
	"\x10dropoff_location\x18\x03 \x01(\v2\x0e.ride.LocationR\x0fdropoffLocation\x12!\n" +
	"\fvehicle_type\x18\x04 \x01(\tR\vvehicleType\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\"I\n" +
	"\x11AcceptRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"H\n" +
	"\x10StartRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"\x82\x01\n" +
	"\x13CompleteRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x125\n" +
	"\x0efinal_location\x18\x03 \x01(\v2\x0e.ride.LocationR\rfinalLocation\"g\n" +
	"\x11CancelRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12!\n" +
	"\fcancelled_by\x18\x02 \x01(\tR\vcancelledBy\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\")\n" +
	"\x0eGetRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\"/\n" +
	"\x14GetActiveRideRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"a\n" +
	"\x15GetRideHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"c\n" +
	"\x16GetRideHistoryResponse\x12(\n" +
	"\x05rides\x18\x01 \x03(\v2\x12.ride.RideResponseR\x05rides\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"u\n" +
	"\x0fRateRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x02R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\",\n" +
	"\x10RateRideResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x89\x01\n" +
	"\x13EstimateRideRequest\x127\n" +
	"\x0fpickup_location\x18\x01 \x01(\v2\x0e.ride.LocationR\x0epickupLocation\x129\n" +
	"\x10dropoff_location\x18\x02 \x01(\v2\x0e.ride.LocationR\x0fdropoffLocation\"H\n" +
	"\x14EstimateRideResponse\x120\n" +
	"\testimates\x18\x01 \x03(\v2\x12.ride.RideEstimateR\testimates\"\xaa\x02\n" +
	"\fRideEstimate\x12!\n" +
	"\fvehicle_type\x18\x01 \x01(\tR\vvehicleType\x12,\n" +
	"\x12estimated_fare_min\x18\x02 \x01(\x01R\x10estimatedFareMin\x12,\n" +
	"\x12estimated_fare_max\x18\x03 \x01(\x01R\x10estimatedFareMax\x12<\n" +
	"\x1aestimated_duration_minutes\x18\x04 \x01(\x01R\x18estimatedDurationMinutes\x122\n" +
	"\x15estimated_distance_km\x18\x05 \x01(\x01R\x13estimatedDistanceKm\x12)\n" +
	"\x10surge_multiplier\x18\x06 \x01(\x01R\x0fsurgeMultiplier\",\n" +
	"\x11StreamRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\"\xe3\x01\n" +
	"\n" +
	"RideUpdate\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.ride.RideStatusR\x06status\x127\n" +
	"\x0fdriver_location\x18\x03 \x01(\v2\x0e.ride.LocationR\x0edriverLocation\x12\x1f\n" +
	"\veta_minutes\x18\x04 \x01(\x01R\n" +
	"etaMinutes\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x83\x06\n" +
	"\fRideResponse\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12(\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.ride.RideStatusR\x06status\x127\n" +
	"\x0fpickup_location\x18\x05 \x01(\v2\x0e.ride.LocationR\x0epickupLocation\x129\n" +
	"\x10dropoff_location\x18\x06 \x01(\v2\x0e.ride.LocationR\x0fdropoffLocation\x12!\n" +
	"\fvehicle_type\x18\a \x01(\tR\vvehicleType\x12%\n" +
	"\x0eestimated_fare\x18\b \x01(\x01R\restimatedFare\x12\x1f\n" +
	"\vactual_fare\x18\t \x01(\x01R\n" +
	"actualFare\x12\x1f\n" +
	"\vdistance_km\x18\n" +
	" \x01(\x01R\n" +
	"distanceKm\x12)\n" +
	"\x10duration_minutes\x18\v \x01(\x01R\x0fdurationMinutes\x12)\n" +
	"\x10surge_multiplier\x18\f \x01(\x01R\x0fsurgeMultiplier\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12%\n" +
	"\x0epayment_method\x18\x10 \x01(\tR\rpaymentMethod\x12!\n" +
	"\frider_rating\x18\x11 \x01(\x02R\vriderRating\x12#\n" +
	"\rdriver_rating\x18\x12 \x01(\x02R\fdriverRating\"^\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress*\x95\x01\n" +
	"\n" +
	"RideStatus\x12\r\n" +
	"\tREQUESTED\x10\x00\x12\v\n" +
	"\aMATCHED\x10\x01\x12\x13\n" +
	"\x0fDRIVER_ACCEPTED\x10\x02\x12\x13\n" +
	"\x0fDRIVER_ARRIVING\x10\x03\x12\x12\n" +
	"\x0eDRIVER_ARRIVED\x10\x04\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x05\x12\r\n" +
	"\tCOMPLETED\x10\x06\x12\r\n" +
	"\tCANCELLED\x10\a2\xb8\x05\n" +
	"\vRideService\x124\n" +
	"\vRequestRide\x12\x11.ride.RideRequest\x1a\x12.ride.RideResponse\x129\n" +
	"\n" +
	"AcceptRide\x12\x17.ride.AcceptRideRequest\x1a\x12.ride.RideResponse\x127\n" +
	"\tStartRide\x12\x16.ride.StartRideRequest\x1a\x12.ride.RideResponse\x12=\n" +
	"\fCompleteRide\x12\x19.ride.CompleteRideRequest\x1a\x12.ride.RideResponse\x129\n" +
	"\n" +
	"CancelRide\x12\x17.ride.CancelRideRequest\x1a\x12.ride.RideResponse\x123\n" +
	"\aGetRide\x12\x14.ride.GetRideRequest\x1a\x12.ride.RideResponse\x12K\n" +
	"\x0eGetRideHistory\x12\x1b.ride.GetRideHistoryRequest\x1a\x1c.ride.GetRideHistoryResponse\x12?\n" +
	"\rGetActiveRide\x12\x1a.ride.GetActiveRideRequest\x1a\x12.ride.RideResponse\x129\n" +
	"\bRateRide\x12\x15.ride.RateRideRequest\x1a\x16.ride.RateRideResponse\x12E\n" +
	"\fEstimateRide\x12\x19.ride.EstimateRideRequest\x1a\x1a.ride.EstimateRideResponse\x12@\n" +
	"\x11StreamRideUpdates\x12\x17.ride.StreamRideRequest\x1a\x10.ride.RideUpdate0\x01B\rZ\vpkg/pb/rideb\x06proto3"

var (
	file_proto_ride_ride_proto_rawDescOnce sync.Once
	file_proto_ride_ride_proto_rawDescData []byte
)

func file_proto_ride_ride_proto_rawDescGZIP() []byte {
	file_proto_ride_ride_proto_rawDescOnce.Do(func() {
		file_proto_ride_ride_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ride_ride_proto_rawDesc), len(file_proto_ride_ride_proto_rawDesc)))
	})
	return file_proto_ride_ride_proto_rawDescData
}

var file_proto_ride_ride_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ride_ride_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_ride_ride_proto_goTypes = []any{
	(RideStatus)(0),                // 0: ride.RideStatus
	(*RideRequest)(nil),            // 1: ride.RideRequest
	(*AcceptRideRequest)(nil),      // 2: ride.AcceptRideRequest
	(*StartRideRequest)(nil),       // 3: ride.StartRideRequest
	(*CompleteRideRequest)(nil),    // 4: ride.CompleteRideRequest
	(*CancelRideRequest)(nil),      // 5: ride.CancelRideRequest
	(*GetRideRequest)(nil),         // 6: ride.GetRideRequest
	(*GetActiveRideRequest)(nil),   // 7: ride.GetActiveRideRequest
	(*GetRideHistoryRequest)(nil),  // 8: ride.GetRideHistoryRequest
	(*GetRideHistoryResponse)(nil), // 9: ride.GetRideHistoryResponse
	(*RateRideRequest)(nil),        // 10: ride.RateRideRequest
	(*RateRideResponse)(nil),       // 11: ride.RateRideResponse
	(*EstimateRideRequest)(nil),    // 12: ride.EstimateRideRequest
	(*EstimateRideResponse)(nil),   // 13: ride.EstimateRideResponse
	(*RideEstimate)(nil),           // 14: ride.RideEstimate
	(*StreamRideRequest)(nil),      // 15: ride.StreamRideRequest
	(*RideUpdate)(nil),             // 16: ride.RideUpdate
	(*RideResponse)(nil),           // 17: ride.RideResponse
	(*Location)(nil),               // 18: ride.Location
	(*timestamppb.Timestamp)(nil),  // 19: google.protobuf.Timestamp
}
var file_proto_ride_ride_proto_depIdxs = []int32{
	18, // 0: ride.RideRequest.pickup_location:type_name -> ride.Location
	18, // 1: ride.RideRequest.dropoff_location:type_name -> ride.Location
	18, // 2: ride.CompleteRideRequest.final_location:type_name -> ride.Location
	17, // 3: ride.GetRideHistoryResponse.rides:type_name -> ride.RideResponse
	18, // 4: ride.EstimateRideRequest.pickup_location:type_name -> ride.Location
	18, // 5: ride.EstimateRideRequest.dropoff_location:type_name -> ride.Location
	14, // 6: ride.EstimateRideResponse.estimates:type_name -> ride.RideEstimate
	0,  // 7: ride.RideUpdate.status:type_name -> ride.RideStatus
	18, // 8: ride.RideUpdate.driver_location:type_name -> ride.Location
	19, // 9: ride.RideUpdate.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 10: ride.RideResponse.status:type_name -> ride.RideStatus
	18, // 11: ride.RideResponse.pickup_location:type_name -> ride.Location
	18, // 12: ride.RideResponse.dropoff_location:type_name -> ride.Location
	19, // 13: ride.RideResponse.created_at:type_name -> google.protobuf.Timestamp
	19, // 14: ride.RideResponse.started_at:type_name -> google.protobuf.Timestamp
	19, // 15: ride.RideResponse.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 16: ride.RideService.RequestRide:input_type -> ride.RideRequest
	2,  // 17: ride.RideService.AcceptRide:input_type -> ride.AcceptRideRequest
	3,  // 18: ride.RideService.StartRide:input_type -> ride.StartRideRequest
	4,  // 19: ride.RideService.CompleteRide:input_type -> ride.CompleteRideRequest
	5,  // 20: ride.RideService.CancelRide:input_type -> ride.CancelRideRequest
	6,  // 21: ride.RideService.GetRide:input_type -> ride.GetRideRequest
	8,  // 22: ride.RideService.GetRideHistory:input_type -> ride.GetRideHistoryRequest
	7,  // 23: ride.RideService.GetActiveRide:input_type -> ride.GetActiveRideRequest
	10, // 24: ride.RideService.RateRide:input_type -> ride.RateRideRequest
	12, // 25: ride.RideService.EstimateRide:input_type -> ride.EstimateRideRequest
	15, // 26: ride.RideService.StreamRideUpdates:input_type -> ride.StreamRideRequest
	17, // 27: ride.RideService.RequestRide:output_type -> ride.RideResponse
	17, // 28: ride.RideService.AcceptRide:output_type -> ride.RideResponse
	17, // 29: ride.RideService.StartRide:output_type -> ride.RideResponse
	17, // 30: ride.RideService.CompleteRide:output_type -> ride.RideResponse
	17, // 31: ride.RideService.CancelRide:output_type -> ride.RideResponse
	17, // 32: ride.RideService.GetRide:output_type -> ride.RideResponse
	9,  // 33: ride.RideService.GetRideHistory:output_type -> ride.GetRideHistoryResponse
	17, // 34: ride.RideService.GetActiveRide:output_type -> ride.RideResponse
	11, // 35: ride.RideService.RateRide:output_type -> ride.RateRideResponse
	13, // 36: ride.RideService.EstimateRide:output_type -> ride.EstimateRideResponse
	16, // 37: ride.RideService.StreamRideUpdates:output_type -> ride.RideUpdate
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_ride_ride_proto_init() }
func file_proto_ride_ride_proto_init() {
	if File_proto_ride_ride_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ride_ride_proto_rawDesc), len(file_proto_ride_ride_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ride_ride_proto_goTypes,
		DependencyIndexes: file_proto_ride_ride_proto_depIdxs,
		EnumInfos:         file_proto_ride_ride_proto_enumTypes,
		MessageInfos:      file_proto_ride_ride_proto_msgTypes,
	}.Build()
	File_proto_ride_ride_proto = out.File
	file_proto_ride_ride_proto_goTypes = nil
	file_proto_ride_ride_proto_depIdxs = nil
}
