// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/ride/ride.proto

package ride

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RideService_RequestRide_FullMethodName       = "/ride.RideService/RequestRide"
	RideService_AcceptRide_FullMethodName        = "/ride.RideService/AcceptRide"
	RideService_StartRide_FullMethodName         = "/ride.RideService/StartRide"
	RideService_CompleteRide_FullMethodName      = "/ride.RideService/CompleteRide"
	RideService_CancelRide_FullMethodName        = "/ride.RideService/CancelRide"
	RideService_GetRide_FullMethodName           = "/ride.RideService/GetRide"
	RideService_GetRideHistory_FullMethodName    = "/ride.RideService/GetRideHistory"
	RideService_GetActiveRide_FullMethodName     = "/ride.RideService/GetActiveRide"
	RideService_RateRide_FullMethodName          = "/ride.RideService/RateRide"
	RideService_EstimateRide_FullMethodName      = "/ride.RideService/EstimateRide"
	RideService_StreamRideUpdates_FullMethodName = "/ride.RideService/StreamRideUpdates"
)

// RideServiceClient is the client API for RideService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RideServiceClient interface {
	RequestRide(ctx context.Context, in *RideRequest, opts ...grpc.CallOption) (*RideResponse, error)
	AcceptRide(ctx context.Context, in *AcceptRideRequest, opts ...grpc.CallOption) (*RideResponse, error)
	StartRide(ctx context.Context, in *StartRideRequest, opts ...grpc.CallOption) (*RideResponse, error)
	CompleteRide(ctx context.Context, in *CompleteRideRequest, opts ...grpc.CallOption) (*RideResponse, error)
	CancelRide(ctx context.Context, in *CancelRideRequest, opts ...grpc.CallOption) (*RideResponse, error)
	GetRide(ctx context.Context, in *GetRideRequest, opts ...grpc.CallOption) (*RideResponse, error)
	GetRideHistory(ctx context.Context, in *GetRideHistoryRequest, opts ...grpc.CallOption) (*GetRideHistoryResponse, error)
	GetActiveRide(ctx context.Context, in *GetActiveRideRequest, opts ...grpc.CallOption) (*RideResponse, error)
	RateRide(ctx context.Context, in *RateRideRequest, opts ...grpc.CallOption) (*RateRideResponse, error)
	EstimateRide(ctx context.Context, in *EstimateRideRequest, opts ...grpc.CallOption) (*EstimateRideResponse, error)
	StreamRideUpdates(ctx context.Context, in *StreamRideRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RideUpdate], error)
}

type rideServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRideServiceClient(cc grpc.ClientConnInterface) RideServiceClient {
	return &rideServiceClient{cc}
}

func (c *rideServiceClient) RequestRide(ctx context.Context, in *RideRequest, opts ...grpc.CallOption) (*RideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RideResponse)
	err := c.cc.Invoke(ctx, RideService_RequestRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) AcceptRide(ctx context.Context, in *AcceptRideRequest, opts ...grpc.CallOption) (*RideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RideResponse)
	err := c.cc.Invoke(ctx, RideService_AcceptRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) StartRide(ctx context.Context, in *StartRideRequest, opts ...grpc.CallOption) (*RideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RideResponse)
	err := c.cc.Invoke(ctx, RideService_StartRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) CompleteRide(ctx context.Context, in *CompleteRideRequest, opts ...grpc.CallOption) (*RideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RideResponse)
	err := c.cc.Invoke(ctx, RideService_CompleteRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) CancelRide(ctx context.Context, in *CancelRideRequest, opts ...grpc.CallOption) (*RideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RideResponse)
	err := c.cc.Invoke(ctx, RideService_CancelRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) GetRide(ctx context.Context, in *GetRideRequest, opts ...grpc.CallOption) (*RideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RideResponse)
	err := c.cc.Invoke(ctx, RideService_GetRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) GetRideHistory(ctx context.Context, in *GetRideHistoryRequest, opts ...grpc.CallOption) (*GetRideHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRideHistoryResponse)
	err := c.cc.Invoke(ctx, RideService_GetRideHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) GetActiveRide(ctx context.Context, in *GetActiveRideRequest, opts ...grpc.CallOption) (*RideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RideResponse)
	err := c.cc.Invoke(ctx, RideService_GetActiveRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) RateRide(ctx context.Context, in *RateRideRequest, opts ...grpc.CallOption) (*RateRideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateRideResponse)
	err := c.cc.Invoke(ctx, RideService_RateRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) EstimateRide(ctx context.Context, in *EstimateRideRequest, opts ...grpc.CallOption) (*EstimateRideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateRideResponse)
	err := c.cc.Invoke(ctx, RideService_EstimateRide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideServiceClient) StreamRideUpdates(ctx context.Context, in *StreamRideRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RideUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RideService_ServiceDesc.Streams[0], RideService_StreamRideUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRideRequest, RideUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RideService_StreamRideUpdatesClient = grpc.ServerStreamingClient[RideUpdate]

// RideServiceServer is the server API for RideService service.
// All implementations must embed UnimplementedRideServiceServer
// for forward compatibility.
type RideServiceServer interface {
	RequestRide(context.Context, *RideRequest) (*RideResponse, error)
	AcceptRide(context.Context, *AcceptRideRequest) (*RideResponse, error)
	StartRide(context.Context, *StartRideRequest) (*RideResponse, error)
	CompleteRide(context.Context, *CompleteRideRequest) (*RideResponse, error)
	CancelRide(context.Context, *CancelRideRequest) (*RideResponse, error)
	GetRide(context.Context, *GetRideRequest) (*RideResponse, error)
	GetRideHistory(context.Context, *GetRideHistoryRequest) (*GetRideHistoryResponse, error)
	GetActiveRide(context.Context, *GetActiveRideRequest) (*RideResponse, error)
	RateRide(context.Context, *RateRideRequest) (*RateRideResponse, error)
	EstimateRide(context.Context, *EstimateRideRequest) (*EstimateRideResponse, error)
	StreamRideUpdates(*StreamRideRequest, grpc.ServerStreamingServer[RideUpdate]) error
	mustEmbedUnimplementedRideServiceServer()
}

// UnimplementedRideServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRideServiceServer struct{}

func (UnimplementedRideServiceServer) RequestRide(context.Context, *RideRequest) (*RideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestRide not implemented")
}
func (UnimplementedRideServiceServer) AcceptRide(context.Context, *AcceptRideRequest) (*RideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptRide not implemented")
}
func (UnimplementedRideServiceServer) StartRide(context.Context, *StartRideRequest) (*RideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRide not implemented")
}
func (UnimplementedRideServiceServer) CompleteRide(context.Context, *CompleteRideRequest) (*RideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteRide not implemented")
}
func (UnimplementedRideServiceServer) CancelRide(context.Context, *CancelRideRequest) (*RideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRide not implemented")
}
func (UnimplementedRideServiceServer) GetRide(context.Context, *GetRideRequest) (*RideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRide not implemented")
}
func (UnimplementedRideServiceServer) GetRideHistory(context.Context, *GetRideHistoryRequest) (*GetRideHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRideHistory not implemented")
}
func (UnimplementedRideServiceServer) GetActiveRide(context.Context, *GetActiveRideRequest) (*RideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveRide not implemented")
}
func (UnimplementedRideServiceServer) RateRide(context.Context, *RateRideRequest) (*RateRideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RateRide not implemented")
}
func (UnimplementedRideServiceServer) EstimateRide(context.Context, *EstimateRideRequest) (*EstimateRideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EstimateRide not implemented")
}
func (UnimplementedRideServiceServer) StreamRideUpdates(*StreamRideRequest, grpc.ServerStreamingServer[RideUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamRideUpdates not implemented")
}
func (UnimplementedRideServiceServer) mustEmbedUnimplementedRideServiceServer() {}
func (UnimplementedRideServiceServer) testEmbeddedByValue()                     {}

// UnsafeRideServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RideServiceServer will
// result in compilation errors.
type UnsafeRideServiceServer interface {
	mustEmbedUnimplementedRideServiceServer()
}

func RegisterRideServiceServer(s grpc.ServiceRegistrar, srv RideServiceServer) {
	// If the following call panics, it indicates UnimplementedRideServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RideService_ServiceDesc, srv)
}

func _RideService_RequestRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).RequestRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_RequestRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).RequestRide(ctx, req.(*RideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_AcceptRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).AcceptRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_AcceptRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).AcceptRide(ctx, req.(*AcceptRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_StartRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).StartRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_StartRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).StartRide(ctx, req.(*StartRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_CompleteRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).CompleteRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_CompleteRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).CompleteRide(ctx, req.(*CompleteRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_CancelRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).CancelRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_CancelRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).CancelRide(ctx, req.(*CancelRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_GetRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).GetRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_GetRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).GetRide(ctx, req.(*GetRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_GetRideHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRideHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).GetRideHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_GetRideHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).GetRideHistory(ctx, req.(*GetRideHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_GetActiveRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).GetActiveRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_GetActiveRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).GetActiveRide(ctx, req.(*GetActiveRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_RateRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).RateRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_RateRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).RateRide(ctx, req.(*RateRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_EstimateRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServiceServer).EstimateRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideService_EstimateRide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServiceServer).EstimateRide(ctx, req.(*EstimateRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideService_StreamRideUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRideRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RideServiceServer).StreamRideUpdates(m, &grpc.GenericServerStream[StreamRideRequest, RideUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RideService_StreamRideUpdatesServer = grpc.ServerStreamingServer[RideUpdate]

// RideService_ServiceDesc is the grpc.ServiceDesc for RideService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RideService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ride.RideService",
	HandlerType: (*RideServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestRide",
			Handler:    _RideService_RequestRide_Handler,
		},
		{
			MethodName: "AcceptRide",
			Handler:    _RideService_AcceptRide_Handler,
		},
		{
			MethodName: "StartRide",
			Handler:    _RideService_StartRide_Handler,
		},
		{
			MethodName: "CompleteRide",
			Handler:    _RideService_CompleteRide_Handler,
		},
		{
			MethodName: "CancelRide",
			Handler:    _RideService_CancelRide_Handler,
		},
		{
			MethodName: "GetRide",
			Handler:    _RideService_GetRide_Handler,
		},
		{
			MethodName: "GetRideHistory",
			Handler:    _RideService_GetRideHistory_Handler,
		},
		{
			MethodName: "GetActiveRide",
			Handler:    _RideService_GetActiveRide_Handler,
		},
		{
			MethodName: "RateRide",
			Handler:    _RideService_RateRide_Handler,
		},
		{
			MethodName: "EstimateRide",
			Handler:    _RideService_EstimateRide_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRideUpdates",
			Handler:       _RideService_StreamRideUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ride/ride.proto",
}
