// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/driver/driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DriverStatus int32

const (
	DriverStatus_OFFLINE   DriverStatus = 0
	DriverStatus_AVAILABLE DriverStatus = 1
	DriverStatus_BUSY      DriverStatus = 2
	DriverStatus_ON_RIDE   DriverStatus = 3
)

// Enum value maps for DriverStatus.
var (
	DriverStatus_name = map[int32]string{
		0: "OFFLINE",
		1: "AVAILABLE",
		2: "BUSY",
		3: "ON_RIDE",
	}
	DriverStatus_value = map[string]int32{
		"OFFLINE":   0,
		"AVAILABLE": 1,
		"BUSY":      2,
		"ON_RIDE":   3,
	}
)

func (x DriverStatus) Enum() *DriverStatus {
	p := new(DriverStatus)
	*p = x
	return p
}

func (x DriverStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_driver_driver_proto_enumTypes[0].Descriptor()
}

func (DriverStatus) Type() protoreflect.EnumType {
	return &file_proto_driver_driver_proto_enumTypes[0]
}

func (x DriverStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverStatus.Descriptor instead.
func (DriverStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{0}
}

type VehicleType int32

const (
	VehicleType_ECONOMY VehicleType = 0
	VehicleType_COMFORT VehicleType = 1
	VehicleType_PREMIUM VehicleType = 2
	VehicleType_SUV     VehicleType = 3
	VehicleType_XL      VehicleType = 4
)

// Enum value maps for VehicleType.
var (
	VehicleType_name = map[int32]string{
		0: "ECONOMY",
		1: "COMFORT",
		2: "PREMIUM",
		3: "SUV",
		4: "XL",
	}
	VehicleType_value = map[string]int32{
		"ECONOMY": 0,
		"COMFORT": 1,
		"PREMIUM": 2,
		"SUV":     3,
		"XL":      4,
	}
)

func (x VehicleType) Enum() *VehicleType {
	p := new(VehicleType)
	*p = x
	return p
}

func (x VehicleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_driver_driver_proto_enumTypes[1].Descriptor()
}

func (VehicleType) Type() protoreflect.EnumType {
	return &file_proto_driver_driver_proto_enumTypes[1]
}

func (x VehicleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleType.Descriptor instead.
func (VehicleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{1}
}

type RegisterDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LicenseNumber string                 `protobuf:"bytes,2,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	Vehicle       *VehicleInfo           `protobuf:"bytes,3,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDriverRequest) Reset() {
	*x = RegisterDriverRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDriverRequest) ProtoMessage() {}

func (x *RegisterDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDriverRequest.ProtoReflect.Descriptor instead.
func (*RegisterDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDriverRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterDriverRequest) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *RegisterDriverRequest) GetVehicle() *VehicleInfo {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type VehicleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Make          string                 `protobuf:"bytes,1,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Year          string                 `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	PlateNumber   string                 `protobuf:"bytes,5,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	VehicleType   VehicleType            `protobuf:"varint,6,opt,name=vehicle_type,json=vehicleType,proto3,enum=driver.VehicleType" json:"vehicle_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleInfo) Reset() {
	*x = VehicleInfo{}
	mi := &file_proto_driver_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleInfo) ProtoMessage() {}

func (x *VehicleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleInfo.ProtoReflect.Descriptor instead.
func (*VehicleInfo) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{1}
}

func (x *VehicleInfo) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *VehicleInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *VehicleInfo) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *VehicleInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *VehicleInfo) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *VehicleInfo) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_ECONOMY
}

type GetDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverRequest) Reset() {
	*x = GetDriverRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverRequest) ProtoMessage() {}

func (x *GetDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverRequest.ProtoReflect.Descriptor instead.
func (*GetDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{2}
}

func (x *GetDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        DriverStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=driver.DriverStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStatusRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() DriverStatus {
	if x != nil {
		return x.Status
	}
	return DriverStatus_OFFLINE
}

type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Heading       float64                `protobuf:"fixed64,4,opt,name=heading,proto3" json:"heading,omitempty"`
	Speed         float64                `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLocationRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateLocationRequest) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *UpdateLocationRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type UpdateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationResponse) Reset() {
	*x = UpdateLocationResponse{}
	mi := &file_proto_driver_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationResponse) ProtoMessage() {}

func (x *UpdateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetNearbyDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	VehicleType   VehicleType            `protobuf:"varint,4,opt,name=vehicle_type,json=vehicleType,proto3,enum=driver.VehicleType" json:"vehicle_type,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyDriversRequest) Reset() {
	*x = GetNearbyDriversRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyDriversRequest) ProtoMessage() {}

func (x *GetNearbyDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyDriversRequest.ProtoReflect.Descriptor instead.
func (*GetNearbyDriversRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{6}
}

func (x *GetNearbyDriversRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetNearbyDriversRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetNearbyDriversRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *GetNearbyDriversRequest) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_ECONOMY
}

func (x *GetNearbyDriversRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetNearbyDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*NearbyDriver        `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyDriversResponse) Reset() {
	*x = GetNearbyDriversResponse{}
	mi := &file_proto_driver_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyDriversResponse) ProtoMessage() {}

func (x *GetNearbyDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyDriversResponse.ProtoReflect.Descriptor instead.
func (*GetNearbyDriversResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{7}
}

func (x *GetNearbyDriversResponse) GetDrivers() []*NearbyDriver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type NearbyDriver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,4,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	Rating        float32                `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Vehicle       *VehicleInfo           `protobuf:"bytes,6,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	EtaMinutes    float64                `protobuf:"fixed64,7,opt,name=eta_minutes,json=etaMinutes,proto3" json:"eta_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyDriver) Reset() {
	*x = NearbyDriver{}
	mi := &file_proto_driver_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyDriver) ProtoMessage() {}

func (x *NearbyDriver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyDriver.ProtoReflect.Descriptor instead.
func (*NearbyDriver) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{8}
}

func (x *NearbyDriver) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *NearbyDriver) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *NearbyDriver) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *NearbyDriver) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *NearbyDriver) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *NearbyDriver) GetVehicle() *VehicleInfo {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *NearbyDriver) GetEtaMinutes() float64 {
	if x != nil {
		return x.EtaMinutes
	}
	return 0
}

type GetDriversByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverIds     []string               `protobuf:"bytes,1,rep,name=driver_ids,json=driverIds,proto3" json:"driver_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversByIdsRequest) Reset() {
	*x = GetDriversByIdsRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversByIdsRequest) ProtoMessage() {}

func (x *GetDriversByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetDriversByIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{9}
}

func (x *GetDriversByIdsRequest) GetDriverIds() []string {
	if x != nil {
		return x.DriverIds
	}
	return nil
}

type GetDriversByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*DriverProfile       `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversByIdsResponse) Reset() {
	*x = GetDriversByIdsResponse{}
	mi := &file_proto_driver_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversByIdsResponse) ProtoMessage() {}

func (x *GetDriversByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetDriversByIdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{10}
}

func (x *GetDriversByIdsResponse) GetDrivers() []*DriverProfile {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type DriverProfile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DriverId         string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LicenseNumber    string                 `protobuf:"bytes,3,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	Vehicle          *VehicleInfo           `protobuf:"bytes,4,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Status           DriverStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=driver.DriverStatus" json:"status,omitempty"`
	Rating           float32                `protobuf:"fixed32,6,opt,name=rating,proto3" json:"rating,omitempty"`
	TotalRides       int32                  `protobuf:"varint,7,opt,name=total_rides,json=totalRides,proto3" json:"total_rides,omitempty"`
	CurrentLatitude  float64                `protobuf:"fixed64,8,opt,name=current_latitude,json=currentLatitude,proto3" json:"current_latitude,omitempty"`
	CurrentLongitude float64                `protobuf:"fixed64,9,opt,name=current_longitude,json=currentLongitude,proto3" json:"current_longitude,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DriverProfile) Reset() {
	*x = DriverProfile{}
	mi := &file_proto_driver_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverProfile) ProtoMessage() {}

func (x *DriverProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverProfile.ProtoReflect.Descriptor instead.
func (*DriverProfile) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{11}
}

func (x *DriverProfile) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DriverProfile) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *DriverProfile) GetVehicle() *VehicleInfo {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *DriverProfile) GetStatus() DriverStatus {
	if x != nil {
		return x.Status
	}
	return DriverStatus_OFFLINE
}

func (x *DriverProfile) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *DriverProfile) GetTotalRides() int32 {
	if x != nil {
		return x.TotalRides
	}
	return 0
}

func (x *DriverProfile) GetCurrentLatitude() float64 {
	if x != nil {
		return x.CurrentLatitude
	}
	return 0
}

func (x *DriverProfile) GetCurrentLongitude() float64 {
	if x != nil {
		return x.CurrentLongitude
	}
	return 0
}

func (x *DriverProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type LocationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationUpdate) Reset() {
	*x = LocationUpdate{}
	mi := &file_proto_driver_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUpdate) ProtoMessage() {}

func (x *LocationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUpdate.ProtoReflect.Descriptor instead.
func (*LocationUpdate) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{12}
}

func (x *LocationUpdate) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *LocationUpdate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationUpdate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_driver_driver_proto protoreflect.FileDescriptor

const file_proto_driver_driver_proto_rawDesc = "" +
	"\n" +
	"\x19proto/driver/driver.proto\x12\x06driver\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n" +
	"\x15RegisterDriverRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0elicense_number\x18\x02 \x01(\tR\rlicenseNumber\x12-\n" +
	"\avehicle\x18\x03 \x01(\v2\x13.driver.VehicleInfoR\avehicle\"\xbc\x01\n" +
	"\vVehicleInfo\x12\x12\n" +
	"\x04make\x18\x01 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x03 \x01(\tR\x04year\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12!\n" +
	"\fplate_number\x18\x05 \x01(\tR\vplateNumber\x126\n" +
	"\fvehicle_type\x18\x06 \x01(\x0e2\x13.driver.VehicleTypeR\vvehicleType\"/\n" +
	"\x10GetDriverRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"`\n" +
	"\x13UpdateStatusRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.driver.DriverStatusR\x06status\"\x9e\x01\n" +
	"\x15UpdateLocationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x01R\aheading\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\"2\n" +
	"\x16UpdateLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xbe\x01\n" +
	"\x17GetNearbyDriversRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\x126\n" +
	"\fvehicle_type\x18\x04 \x01(\x0e2\x13.driver.VehicleTypeR\vvehicleType\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"J\n" +
	"\x18GetNearbyDriversResponse\x12.\n" +
	"\adrivers\x18\x01 \x03(\v2\x14.driver.NearbyDriverR\adrivers\"\xee\x01\n" +
	"\fNearbyDriver\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1f\n" +
	"\vdistance_km\x18\x04 \x01(\x01R\n" +
	"distanceKm\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x02R\x06rating\x12-\n" +
	"\avehicle\x18\x06 \x01(\v2\x13.driver.VehicleInfoR\avehicle\x12\x1f\n" +
	"\veta_minutes\x18\a \x01(\x01R\n" +
	"etaMinutes\"7\n" +
	"\x16GetDriversByIdsRequest\x12\x1d\n" +
	"\n" +
	"driver_ids\x18\x01 \x03(\tR\tdriverIds\"J\n" +
	"\x17GetDriversByIdsResponse\x12/\n" +
	"\adrivers\x18\x01 \x03(\v2\x15.driver.DriverProfileR\adrivers\"\x95\x03\n" +
	"\rDriverProfile\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0elicense_number\x18\x03 \x01(\tR\rlicenseNumber\x12-\n" +
	"\avehicle\x18\x04 \x01(\v2\x13.driver.VehicleInfoR\avehicle\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.driver.DriverStatusR\x06status\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x02R\x06rating\x12\x1f\n" +
	"\vtotal_rides\x18\a \x01(\x05R\n" +
	"totalRides\x12)\n" +
	"\x10current_latitude\x18\b \x01(\x01R\x0fcurrentLatitude\x12+\n" +
	"\x11current_longitude\x18\t \x01(\x01R\x10currentLongitude\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa1\x01\n" +
	"\x0eLocationUpdate\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*A\n" +
	"\fDriverStatus\x12\v\n" +
	"\aOFFLINE\x10\x00\x12\r\n" +
	"\tAVAILABLE\x10\x01\x12\b\n" +
	"\x04BUSY\x10\x02\x12\v\n" +
	"\aON_RIDE\x10\x03*E\n" +
	"\vVehicleType\x12\v\n" +
	"\aECONOMY\x10\x00\x12\v\n" +
	"\aCOMFORT\x10\x01\x12\v\n" +
	"\aPREMIUM\x10\x02\x12\a\n" +
	"\x03SUV\x10\x03\x12\x06\n" +
	"\x02XL\x10\x042\xa8\x04\n" +
	"\rDriverService\x12F\n" +
	"\x0eRegisterDriver\x12\x1d.driver.RegisterDriverRequest\x1a\x15.driver.DriverProfile\x12<\n" +
	"\tGetDriver\x12\x18.driver.GetDriverRequest\x1a\x15.driver.DriverProfile\x12B\n" +
	"\fUpdateStatus\x12\x1b.driver.UpdateStatusRequest\x1a\x15.driver.DriverProfile\x12O\n" +
	"\x0eUpdateLocation\x12\x1d.driver.UpdateLocationRequest\x1a\x1e.driver.UpdateLocationResponse\x12U\n" +
	"\x10GetNearbyDrivers\x12\x1f.driver.GetNearbyDriversRequest\x1a .driver.GetNearbyDriversResponse\x12R\n" +
	"\x0fGetDriversByIds\x12\x1e.driver.GetDriversByIdsRequest\x1a\x1f.driver.GetDriversByIdsResponse\x12Q\n" +
	"\x14StreamDriverLocation\x12\x1d.driver.UpdateLocationRequest\x1a\x16.driver.LocationUpdate(\x010\x01B\x0fZ\rpkg/pb/driverb\x06proto3"

var (
	file_proto_driver_driver_proto_rawDescOnce sync.Once
	file_proto_driver_driver_proto_rawDescData []byte
)

func file_proto_driver_driver_proto_rawDescGZIP() []byte {
	file_proto_driver_driver_proto_rawDescOnce.Do(func() {
		file_proto_driver_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_driver_driver_proto_rawDesc), len(file_proto_driver_driver_proto_rawDesc)))
	})
	return file_proto_driver_driver_proto_rawDescData
}

var file_proto_driver_driver_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_driver_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_driver_driver_proto_goTypes = []any{
	(DriverStatus)(0),                // 0: driver.DriverStatus
	(VehicleType)(0),                 // 1: driver.VehicleType
	(*RegisterDriverRequest)(nil),    // 2: driver.RegisterDriverRequest
	(*VehicleInfo)(nil),              // 3: driver.VehicleInfo
	(*GetDriverRequest)(nil),         // 4: driver.GetDriverRequest
	(*UpdateStatusRequest)(nil),      // 5: driver.UpdateStatusRequest
	(*UpdateLocationRequest)(nil),    // 6: driver.UpdateLocationRequest
	(*UpdateLocationResponse)(nil),   // 7: driver.UpdateLocationResponse
	(*GetNearbyDriversRequest)(nil),  // 8: driver.GetNearbyDriversRequest
	(*GetNearbyDriversResponse)(nil), // 9: driver.GetNearbyDriversResponse
	(*NearbyDriver)(nil),             // 10: driver.NearbyDriver
	(*GetDriversByIdsRequest)(nil),   // 11: driver.GetDriversByIdsRequest
	(*GetDriversByIdsResponse)(nil),  // 12: driver.GetDriversByIdsResponse
	(*DriverProfile)(nil),            // 13: driver.DriverProfile
	(*LocationUpdate)(nil),           // 14: driver.LocationUpdate
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_proto_driver_driver_proto_depIdxs = []int32{
	3,  // 0: driver.RegisterDriverRequest.vehicle:type_name -> driver.VehicleInfo
	1,  // 1: driver.VehicleInfo.vehicle_type:type_name -> driver.VehicleType
	0,  // 2: driver.UpdateStatusRequest.status:type_name -> driver.DriverStatus
	1,  // 3: driver.GetNearbyDriversRequest.vehicle_type:type_name -> driver.VehicleType
	10, // 4: driver.GetNearbyDriversResponse.drivers:type_name -> driver.NearbyDriver
	3,  // 5: driver.NearbyDriver.vehicle:type_name -> driver.VehicleInfo
	13, // 6: driver.GetDriversByIdsResponse.drivers:type_name -> driver.DriverProfile
	3,  // 7: driver.DriverProfile.vehicle:type_name -> driver.VehicleInfo
	0,  // 8: driver.DriverProfile.status:type_name -> driver.DriverStatus
	15, // 9: driver.DriverProfile.created_at:type_name -> google.protobuf.Timestamp
	15, // 10: driver.LocationUpdate.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 11: driver.DriverService.RegisterDriver:input_type -> driver.RegisterDriverRequest
	4,  // 12: driver.DriverService.GetDriver:input_type -> driver.GetDriverRequest
	5,  // 13: driver.DriverService.UpdateStatus:input_type -> driver.UpdateStatusRequest
	6,  // 14: driver.DriverService.UpdateLocation:input_type -> driver.UpdateLocationRequest
	8,  // 15: driver.DriverService.GetNearbyDrivers:input_type -> driver.GetNearbyDriversRequest
	11, // 16: driver.DriverService.GetDriversByIds:input_type -> driver.GetDriversByIdsRequest
	6,  // 17: driver.DriverService.StreamDriverLocation:input_type -> driver.UpdateLocationRequest
	13, // 18: driver.DriverService.RegisterDriver:output_type -> driver.DriverProfile
	13, // 19: driver.DriverService.GetDriver:output_type -> driver.DriverProfile
	13, // 20: driver.DriverService.UpdateStatus:output_type -> driver.DriverProfile
	7,  // 21: driver.DriverService.UpdateLocation:output_type -> driver.UpdateLocationResponse
	9,  // 22: driver.DriverService.GetNearbyDrivers:output_type -> driver.GetNearbyDriversResponse
	12, // 23: driver.DriverService.GetDriversByIds:output_type -> driver.GetDriversByIdsResponse
	14, // 24: driver.DriverService.StreamDriverLocation:output_type -> driver.LocationUpdate
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_driver_driver_proto_init() }
func file_proto_driver_driver_proto_init() {
	if File_proto_driver_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_driver_driver_proto_rawDesc), len(file_proto_driver_driver_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_driver_driver_proto_goTypes,
		DependencyIndexes: file_proto_driver_driver_proto_depIdxs,
		EnumInfos:         file_proto_driver_driver_proto_enumTypes,
		MessageInfos:      file_proto_driver_driver_proto_msgTypes,
	}.Build()
	File_proto_driver_driver_proto = out.File
	file_proto_driver_driver_proto_goTypes = nil
	file_proto_driver_driver_proto_depIdxs = nil
}
